{{- with .Values.imagePullSecret }}
{{- if and .name .registry .username .password }}
{{- $auth := printf "%s:%s" .username .password | b64enc }}
{{- $dockerconfig := dict "auths" (dict .registry (dict "auth" $auth)) | toJson | b64enc }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "nico.labels" $ | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: before-hook-creation
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $dockerconfig | quote }}
{{- end }}
{{- end }}
