apiVersion: v1
kind: Secret
metadata:
  name: ssh-host-key
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nico.labels" . | nindent 4 }}
type: Opaque
data:
  ssh_host_ed25519_key: {{ .Values.sshConsoleHostKey | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: carbide-vault-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nico.labels" . | nindent 4 }}
type: Opaque
data:
  token: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: nico-vault-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nico.labels" . | nindent 4 }}
type: Opaque
data:
  token: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: nico-vault-approle-tokens
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nico.labels" . | nindent 4 }}
type: Opaque
data: {}
