apiVersion: v1
kind: Service
metadata:
  name: vault-ui-lb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nico.labels" . | nindent 4 }}
    app.kubernetes.io/component: vault-ui
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.metallb.vaultIP | quote }}
  externalTrafficPolicy: Local
  ports:
    - name: https
      port: 443
      targetPort: 8200
      protocol: TCP
  selector:
    app.kubernetes.io/name: vault
    component: server
