apiVersion: k0rdent.mirantis.com/v1beta1
kind: ServiceTemplate
metadata:
  name: cert-manager-1-20-2
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: cert-manager
      version: 1.20.2
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: kcm-templates
