apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ProviderTemplate
metadata:
  name: cluster-api-provider-ipam-0-1-0
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: cluster-api-provider-ipam
      version: 0.1.0
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: kcm-templates
