apiVersion: k0rdent.mirantis.com/v1beta1
kind: ServiceTemplate
metadata:
  name: metallb-0-16-1
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: metallb
      version: 0.16.1
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: kcm-templates
