apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSCluster
metadata:
  name: {{ include "cluster.name" . }}
  annotations:
    aws.cluster.x-k8s.io/external-resource-gc: "true"
  finalizers:
    - k0rdent.mirantis.com/cleanup
spec:
  region: {{ .Values.region }}
  identityRef:
    kind: {{ .Values.clusterIdentity.kind }}
    name: {{ .Values.clusterIdentity.name }}
  controlPlaneLoadBalancer:
    healthCheckProtocol: TCP
  network:
    vpc:
      id: vpc-055f9b6887200e89d
    subnets:
      - id: subnet-03a992d2e3079e98b
        availabilityZone: us-west-1c
        isPublic: true
      - id: subnet-0084498af17c05d93
        availabilityZone: us-west-1c
        isPublic: false
      - id: subnet-07d7117f5fa03fb8e
        availabilityZone: us-west-1b
        isPublic: true
      - id: subnet-04aa20824fd313eb3
        availabilityZone: us-west-1b
        isPublic: false
    additionalControlPlaneIngressRules:
      - description: "k0s controller join API"
        protocol: tcp
        fromPort: 9443
        toPort: 9443
  {{- if not (quote .Values.sshKeyName | empty) }}
  sshKeyName: {{ .Values.sshKeyName | quote }}
  {{- end }}
  {{- with .Values.bastion }}
  bastion:
    {{- toYaml . | nindent 4 }}
  {{- end }}
