apiVersion: v2
name: local-path-provisioner
description: Rancher local-path-provisioner — provides a default StorageClass backed by node-local directories.
type: application
version: 0.1.0
appVersion: "v20241212-8ac705d0"
