apiVersion: k0rdent.mirantis.com/v1alpha1
kind: Release
metadata:
  name: kcm-0-1-0
  annotations:
    helm.sh/resource-policy: keep
spec:
  version: 0.1.0
  kcm:
    template: kcm-0-1-0
  capi:
    template: cluster-api-0-1-2
  providers:
    - name: k0smotron
      template: k0smotron-0-1-1
    - name: cluster-api-provider-azure
      template: cluster-api-provider-azure-0-1-1
    - name: cluster-api-provider-vsphere
      template: cluster-api-provider-vsphere-0-1-0
    - name: cluster-api-provider-aws
      template: cluster-api-provider-aws-0-1-0
    - name: cluster-api-provider-openstack
      template: cluster-api-provider-openstack-0-1-4
    - name: cluster-api-provider-docker
      template: cluster-api-provider-docker-0-1-3
    - name: cluster-api-provider-gcp
      template: cluster-api-provider-gcp-0-1-0
    - name: cluster-api-provider-ipam
      template: cluster-api-provider-ipam-0-1-0
    - name: projectsveltos
      template: projectsveltos-0-50-0
