# permissions for end users to edit managementbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kcm.fullname" . }}-ipam-editor-role
rules:
- apiGroups:
  - k0rdent.mirantis.com
  resources:
  - clusteripamclaims
  - clusteripamclaims/status
  verbs: {{ include "rbac.editorVerbs" . | nindent 6 }}
