# permissions for end users to view managementbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kcm.fullname" . }}-ipam-viewer-role
  labels:
    k0rdent.mirantis.com/aggregate-to-namespace-viewer: "true"
rules:
- apiGroups:
  - k0rdent.mirantis.com
  resources:
    - clusteripamclaims
    - clusteripamclaims/status
    - clusteripams
    - clusteripams/status
  verbs: {{ include "rbac.viewerVerbs" . | nindent 6 }}
