apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterDeployment
metadata:
  name: aws-${CLUSTER_NAME_SUFFIX}
  namespace: ${NAMESPACE}
spec:
  ipamClaim:
    spec:
      provider: ipam-aws
      nodeNetwork:
        ipAddresses: [ 10.0.0.36 ]
        gateway: 172.16.40.1
        prefix: 24
  template: aws-standalone-cp-1-0-10
  credential: aws-cluster-identity-cred
  config:
    clusterLabels: {}
    clusterAnnotations: {}
    controlPlane:
      instanceType: t3.small
    controlPlaneNumber: 1
    publicIP: false
    region: ${AWS_REGION}
    worker:
      instanceType: t3.small
    workersNumber: 1
