---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSClusterStaticIdentity
metadata:
  name: aws-cluster-identity
  namespace: ${NAMESPACE}
  labels:
    k0rdent.mirantis.com/component: "kcm"
spec:
  secretRef: aws-cluster-identity-secret
  allowedNamespaces:
    list:
      - ${NAMESPACE}
    selector:
      matchLabels: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-cluster-identity-secret
  namespace: ${NAMESPACE}
  labels:
    k0rdent.mirantis.com/component: "kcm"
type: Opaque
stringData:
  AccessKeyID: ${AWS_ACCESS_KEY_ID}
  SecretAccessKey: ${AWS_SECRET_ACCESS_KEY}
  SessionToken: ${AWS_SESSION_TOKEN}
---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: Credential
metadata:
  name: aws-cluster-identity-cred
  namespace: ${NAMESPACE}
spec:
  description: AWS credentials
  identityRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
    kind: AWSClusterStaticIdentity
    name: aws-cluster-identity
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-cluster-identity-resource-template
  namespace: ${NAMESPACE}
  labels:
    k0rdent.mirantis.com/component: "kcm"
  annotations:
    projectsveltos.io/template: "true"
