apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterDeployment
metadata:
  name: docker-${CLUSTER_NAME_SUFFIX}
  namespace: ${NAMESPACE}
spec:
  template: docker-hosted-cp-1-0-10
  credential: docker-stub-credential
  config:
    clusterLabels: {}
    clusterAnnotations: {}
  serviceSpec:
    services:
      - template: cert-manager-1-20-2
        name: cert-manager
        namespace: cert-manager
        helmOptions:
          installOptions:
            createNamespace: true
      - template: metallb-0-16-1
        name: metallb
        namespace: metallb
        helmOptions:
          installOptions:
            createNamespace: true
      - template: local-path-provisioner-0-1-0
        name: local-path-provisioner
        namespace: local-path-storage
        helmOptions:
          installOptions:
            createNamespace: true
      - template: nico-0-1-9
        name: nico
        namespace: nico
        helmOptions:
          installOptions:
            createNamespace: true
        values: |
          devMode: true
          vault:
            global:
              tlsDisable: true
            server:
              dev:
                enabled: true
          postgresql:
            tls:
              enabled: false
          global:
            image:
              repository: kcm-local-registry:5000/nico/nico
              tag: "0.9.1-amd64"
              pullPolicy: IfNotPresent
        dependsOn:
          - name: cert-manager
            namespace: cert-manager
          - name: metallb
            namespace: metallb
          - name: local-path-provisioner
            namespace: local-path-storage
