apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterDeployment
metadata:
  name: docker-${CLUSTER_NAME_SUFFIX}
  namespace: ${NAMESPACE}
spec:
  template: docker-hosted-cp-1-0-11
  credential: docker-stub-credential
  config:
    clusterLabels: {}
    clusterAnnotations: {}
    k0s:
      insecureRegistries:
        - host: kcm-local-registry:5000
      workerArgs:
        - "--cri-socket=remote:unix:///run/containerd/containerd.sock"
      extraWorkerFiles:
        - path: /etc/containerd/certs.d/kcm-local-registry:5000/hosts.toml
          content: |
            server = "http://kcm-local-registry:5000"

            [host."http://kcm-local-registry:5000"]
              capabilities = ["pull", "resolve", "push"]
              skip_verify = true
  serviceSpec:
    services:
      - template: cert-manager-1-20-2
        name: cert-manager
        namespace: cert-manager
        helmOptions:
          installOptions:
            createNamespace: true
      - template: metallb-0-16-1
        name: metallb
        namespace: metallb
        helmOptions:
          installOptions:
            createNamespace: true
      - template: local-path-provisioner-0-1-0
        name: local-path-provisioner
        namespace: local-path-storage
        helmOptions:
          installOptions:
            createNamespace: true
      - template: nico-0-1-17
       # templateChain: nico-chain
        name: nico
        namespace: nico
        helmOptions:
          installOptions:
            createNamespace: true
        values: |
          devMode: true
          global:
            devMode: true
            image:
              repository: kcm-local-registry:5000/nico/nico
              tag: "0.9.1-amd64"
              pullPolicy: IfNotPresent
          vault:
            global:
              tlsDisable: true
            server:
              dev:
                enabled: true
          postgresql:
            tls:
              enabled: false
          nico-app:
            nico-pxe:
              enabled: true
              bootArtifactContainers:
                - name: boot-artifacts-x86-64
                  image: kcm-local-registry:5000/boot-artifacts-x86_64:effd786
                  command: ["sh", "-c", "cp -r /x86_64 /boot-artifacts/blobs/internal"]
        dependsOn:
          - name: cert-manager
            namespace: cert-manager
          - name: metallb
            namespace: metallb
          - name: local-path-provisioner
            namespace: local-path-storage
