apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureCluster
metadata:
  name: {{ include "cluster.name" . }}
  finalizers:
    - k0rdent.mirantis.com/cleanup
spec:
  {{- with .Values.clusterIdentity }}
  identityRef:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  location: {{ .Values.location }}
  {{- if .Values.bastion.enabled }}
  {{- with .Values.bastion.bastionSpec }}
  bastionSpec:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  subscriptionID: {{ .Values.subscriptionID }}
  networkSpec:
    vnet:
      name: my-vnet
      cidrBlocks:
        - 10.0.0.0/30
