apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPMachineTemplate
metadata:
  name: {{ include "gcpmachinetemplate.worker.name" . }}
  annotations:
    huge: "test"
spec:
  template:
    spec:
      {{- with .Values.worker }}
      ipAddress: "10.150.15.200"
      instanceType: {{ .instanceType }}
      subnet: {{ .subnet }}
      providerID: {{ .providerID }}
      imageFamily: {{ .imageFamily }}
      image: {{ .image }}
      {{- if .additionalLabels }}
      additionalLabels: {{- toYaml .additionalLabels | nindent 8 }}
      {{- end }}
      publicIP: {{ .publicIP }}
      {{- if .additionalNetworkTags }}
      additionalNetworkTags: {{- toYaml .additionalNetworkTags | nindent 8 }}
      {{- end }}
      rootDeviceSize: {{ .rootDeviceSize }}
      rootDeviceType: {{ .rootDeviceType }}
      serviceAccount:
        email: {{ .serviceAccount.email }}
        scopes: {{- toYaml .serviceAccount.scopes | nindent 10 }}
      ipForwarding: {{ .ipForwarding }}
      {{- end }}
